name: Check & fix styling

on: [push]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
          verboseMode: true
          onlyDirty: true
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
          commit_options: '--no-verify'
          file_pattern: '*.php'
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHP info
        run: |
          php --version
          php -m
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Composer install
        uses: php-actions/composer@v6
      - name: Setup `.env` File
        shell: bash
        run: |
          cp .env.example .env
      - name: Check namespaces
        run: php artisan check:psr4

